# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/tbent/projects/archive/viscrupt/dg_waves_defunct

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/tbent/projects/archive/viscrupt/dg_waves_defunct

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tbent/projects/archive/viscrupt/dg_waves_defunct/CMakeFiles /home/tbent/projects/archive/viscrupt/dg_waves_defunct/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/tbent/projects/archive/viscrupt/dg_waves_defunct/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named viscosaur

# Build rule for target.
viscosaur: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 viscosaur
.PHONY : viscosaur

# fast build rule for target.
viscosaur/fast:
	$(MAKE) -f CMakeFiles/viscosaur.dir/build.make CMakeFiles/viscosaur.dir/build
.PHONY : viscosaur/fast

control.o: control.cc.o
.PHONY : control.o

# target to build an object file
control.cc.o:
	$(MAKE) -f CMakeFiles/viscosaur.dir/build.make CMakeFiles/viscosaur.dir/control.cc.o
.PHONY : control.cc.o

control.i: control.cc.i
.PHONY : control.i

# target to preprocess a source file
control.cc.i:
	$(MAKE) -f CMakeFiles/viscosaur.dir/build.make CMakeFiles/viscosaur.dir/control.cc.i
.PHONY : control.cc.i

control.s: control.cc.s
.PHONY : control.s

# target to generate assembly for a file
control.cc.s:
	$(MAKE) -f CMakeFiles/viscosaur.dir/build.make CMakeFiles/viscosaur.dir/control.cc.s
.PHONY : control.cc.s

dg.o: dg.cc.o
.PHONY : dg.o

# target to build an object file
dg.cc.o:
	$(MAKE) -f CMakeFiles/viscosaur.dir/build.make CMakeFiles/viscosaur.dir/dg.cc.o
.PHONY : dg.cc.o

dg.i: dg.cc.i
.PHONY : dg.i

# target to preprocess a source file
dg.cc.i:
	$(MAKE) -f CMakeFiles/viscosaur.dir/build.make CMakeFiles/viscosaur.dir/dg.cc.i
.PHONY : dg.cc.i

dg.s: dg.cc.s
.PHONY : dg.s

# target to generate assembly for a file
dg.cc.s:
	$(MAKE) -f CMakeFiles/viscosaur.dir/build.make CMakeFiles/viscosaur.dir/dg.cc.s
.PHONY : dg.cc.s

python_interface.o: python_interface.cc.o
.PHONY : python_interface.o

# target to build an object file
python_interface.cc.o:
	$(MAKE) -f CMakeFiles/viscosaur.dir/build.make CMakeFiles/viscosaur.dir/python_interface.cc.o
.PHONY : python_interface.cc.o

python_interface.i: python_interface.cc.i
.PHONY : python_interface.i

# target to preprocess a source file
python_interface.cc.i:
	$(MAKE) -f CMakeFiles/viscosaur.dir/build.make CMakeFiles/viscosaur.dir/python_interface.cc.i
.PHONY : python_interface.cc.i

python_interface.s: python_interface.cc.s
.PHONY : python_interface.s

# target to generate assembly for a file
python_interface.cc.s:
	$(MAKE) -f CMakeFiles/viscosaur.dir/build.make CMakeFiles/viscosaur.dir/python_interface.cc.s
.PHONY : python_interface.cc.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... viscosaur"
	@echo "... control.o"
	@echo "... control.i"
	@echo "... control.s"
	@echo "... dg.o"
	@echo "... dg.i"
	@echo "... dg.s"
	@echo "... python_interface.o"
	@echo "... python_interface.i"
	@echo "... python_interface.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

